# Matugen dynamic theme
include colors.conf

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

allow_remote_control yes
listen_on unix:@kitty

window_padding_width 8
background_opacity 0.8
font_size 11

cursor_shape beam
cursor_trail 1

# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
