#!/usr/bin/env python3
"""Synchronize Material Shell theme colors with Hyprland."""
import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

FALLBACK = {
    'light': {
        'primary': '#35618e',
        'primary_container': '#d1e4ff',
        'outline': '#73777f',
    },
    'dark': {
        'primary': '#b4cea5',
        'primary_container': '#3c4b37',
        'outline': '#8e9387',
    },
}

STATE_DIR = Path(os.environ.get('XDG_STATE_HOME', str(Path.home() / '.local/state'))) / 'material-shell'
CONFIG_DIR = Path(os.environ.get('XDG_CONFIG_HOME', str(Path.home() / '.config'))) / 'material-shell'
HYPR_CONFIG_DIR = Path(os.environ.get('XDG_CONFIG_HOME', str(Path.home() / '.config'))) / 'hypr'


def hex_to_rgba(hex_code, alpha='ff'):
    if not isinstance(hex_code, str):
        return None
    cleaned = hex_code.strip().lstrip('#')
    if not re.fullmatch(r'[0-9a-fA-F]{6}', cleaned):
        return None
    return f'rgba({cleaned.lower()}{alpha})'


def load_palette():
    state_file = STATE_DIR / 'palette.json'
    try:
        data = json.loads(state_file.read_text())
        if data.get('version') == 2 and isinstance(data.get('schemes'), dict):
            return data['schemes']
    except (OSError, ValueError, KeyError):
        pass
    return None


def load_mode():
    config_file = CONFIG_DIR / 'settings.json'
    try:
        data = json.loads(config_file.read_text())
        mode = data.get('themeMode')
        if mode in ('light', 'dark'):
            return mode
    except (OSError, ValueError, KeyError):
        pass
    return 'dark'


def resolve_colors(palette=None, mode=None):
    if mode not in ('light', 'dark'):
        mode = load_mode()

    schemes = None
    if isinstance(palette, dict):
        if 'schemes' in palette and isinstance(palette['schemes'], dict):
            schemes = palette['schemes']
        elif 'light' in palette and 'dark' in palette:
            schemes = palette
        elif 'primary' in palette:
            schemes = {mode: palette}
    if not schemes and palette is None:
        schemes = load_palette()

    scheme = (schemes.get(mode) if schemes else None) or FALLBACK[mode]

    fb = FALLBACK[mode]
    c_primary = scheme.get('primary') or fb['primary']
    c_primary_container = scheme.get('primary_container') or fb['primary_container']
    c_outline = scheme.get('outline') or fb['outline']

    rgba_active1 = hex_to_rgba(c_primary, 'ee') or hex_to_rgba(fb['primary'], 'ee')
    rgba_active2 = hex_to_rgba(c_primary_container, 'ee') or hex_to_rgba(fb['primary_container'], 'ee')
    rgba_inactive = hex_to_rgba(c_outline, 'aa') or hex_to_rgba(fb['outline'], 'aa')

    return {
        'active_border_1': rgba_active1,
        'active_border_2': rgba_active2,
        'inactive_border': rgba_inactive,
    }


def generate_lua(colors):
    c1 = colors['active_border_1']
    c2 = colors['active_border_2']
    c3 = colors['inactive_border']
    return (
        "-- Auto-generated by Material Shell. Do not edit manually.\n"
        "hl.config({\n"
        "    general = {\n"
        "        col = {\n"
        "            active_border = {\n"
        f"                colors = {{ \"{c1}\", \"{c2}\" }},\n"
        "                angle = 45,\n"
        "            },\n"
        f"            inactive_border = \"{c3}\",\n"
        "        },\n"
        "    },\n"
        "})\n"
    )


def save_config(colors, config_dir=None):
    dest_dir = Path(config_dir) if config_dir else HYPR_CONFIG_DIR
    dest_dir.mkdir(parents=True, exist_ok=True)
    target = dest_dir / 'theme.lua'
    content = generate_lua(colors)
    with tempfile.NamedTemporaryFile('w', dir=dest_dir, prefix='.theme-', delete=False) as f:
        f.write(content)
        f.flush()
        os.fsync(f.fileno())
        temp_name = f.name
    os.replace(temp_name, target)


def apply_runtime(colors):
    c1 = colors['active_border_1']
    c2 = colors['active_border_2']
    c3 = colors['inactive_border']
    lua = (
        f'hl.config({{ general = {{ col = {{ '
        f'active_border = {{ colors = {{"{c1}", "{c2}"}}, angle = 45 }}, '
        f'inactive_border = "{c3}" '
        f'}} }} }})'
    )
    binary = shutil.which('hyprctl')
    if not binary:
        return False
    try:
        res = subprocess.run([binary, 'eval', lua], capture_output=True, text=True, timeout=5)
        return res.returncode == 0
    except (subprocess.SubprocessError, OSError):
        return False


def apply(palette=None, mode=None, config_dir=None):
    colors = resolve_colors(palette=palette, mode=mode)
    try:
        save_config(colors, config_dir=config_dir)
    except OSError:
        pass
    apply_runtime(colors)
    return colors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--mode', choices=['light', 'dark'], help='Theme mode to apply')
    args = parser.parse_args()
    colors = apply(mode=args.mode)
    print(f"Hyprland theme updated: {colors}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
